In [1]:
import numpy as np
import os
import time

In [3]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)

[1 2 3 4 5 6]


In [4]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
# explain about dimension of the array
print(a.shape)
print(a.ndim)
print(a.size)

(3, 4)
2
12


In [26]:
a = np.zeros((2, 3))
print(a)

In [27]:
a = np.ones((2, 3))
print(a)

In [28]:
a = np.arange(7)
print(a)

# [0, 3, 6, 9]

In [29]:
# start, stop, step
a = np.arange(2, 9, 1)
print(a)

In [30]:
a = np.sort(a)
print(a)

In [31]:
#explain concatenate

x = np.array([[1, 2], [3, 4], [10, 11]])
y = np.array([[5, 6], [7, 8]])
z = np.concatenate((x, y), axis = 0)
print(z)

# put axis = 1 and show the output

In [32]:
a = np.arange(6)
print(a)

b = a.reshape(2, 3)
print(b)

# a.reshape(3, 3) won't be possible but a.reshape(3, -1) will be equivalent to dividing a into 3 equal rows that is a.reshape(3, 2).

In [33]:
# slice operation
a = np.array([1, 2, 3])
b = a[0 : 2]
print(b)

c = a[0 : ]
print(c)

a = np.array([[-1, 0, 1, 0],[2, -3, 0, 1],[0, 4, -2, 1]])
print(a[0:3, 2:4])

# [-1 0 1 0]
# [2 -3 0 1]
# [0 4 -2 1]

In [34]:
a = np.array([1,8,3,2,1,9,7])
b = a[1:] - a[:-1]
print(b)

# Vector of first differences. Here we use slicing to create an (n − 1)-vector d which is defined as the first difference vector di = xi+1 − xi
# for i = 1, . . . , n − 1, where x is an n-vector.

In [35]:
# data = np.array([1, 2, 3, 4])
# ones = np.ones(1, dtype = int)
# print(ones)
# print(data + ones)

# it will broadcast the 1's to all the elements of data.

# data = np.array([1, 2])
# ones = np.ones(2, dtype = int)
# print(ones)
# print(data + ones)

# size of array ones is equal to size of array data, so direct addition will happen

# this will give error because size of ones is greater than data array size
data = np.array([1, 2, 3])
ones = np.ones(3, dtype = int)
print(data + ones)

In [36]:
data = np.array([1.0, 2.0])
print(data * 1.6)

In [37]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
b = np.transpose(a)
print(b)

In [38]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = a.flatten()
b[0] = 13
print(a[0][0])


In [39]:
# ravel() is same as flatten() but now changes in the element of b will also be changed in array a
b = a.ravel()
print(b)

b[0] = 13
a[0][0] = 14 
print(b[0])

In [40]:
a = np.ones([9, 7, 4])
b = np.ones([9, 4, 3])
c = np.dot(a, b)
print(c.shape)

d = np.matmul(a, b)
print(d.shape)

In [41]:
a = np.array([-1.1, 0.0, 3.6, -7.2])
# to do shallow copy
b = a.copy()

# to do deep copy
b = a

a[2] = 20.0
print(b)

In [42]:
# Random vectors. Sometimes it is useful to generate random vectors to check our algorithm or test an identity. 
# In Python, we generate a random vector of size n using
# np.random.random(n).
print(np.random.random((4,1)))

In [43]:
# elementwise operations between 2 vectors
a = np.array([1,2,3])
b = np.array([100,200,300])
print('Sum of arrays:', a + b)
print('Difference of arrays:', a - b)

a_initial = np.array([1, 2, 3])
a_final = np.array([3, 6, 9])
b = (a_final - a_initial) / a_initial
print(b)

In [44]:
# linear combination
a = np.array([1, 2])
b = np.array([3, 4])
alpha = -0.5
beta = 1.5
c = alpha * a + beta * b
print(c)

In [45]:
a = np.random.random(10**5)
b = np.random.random(10**5)
start = time.time()

# @ function is matrix multiplication
a @ b
end = time.time()
print(end - start)

# Check Time Taken by a operations, this is measured in seconds

In [46]:
# Different ways to calculate norm

a = np.array([2,-1,2])
print(np.linalg.norm(a))
print(np.sqrt(np.inner(a, a)))
print((sum(a**2)**0.5))

In [47]:
# Triangle Inequality

a = np.random.random(10)
b = np.random.random(10)
LHS = np.linalg.norm(a + b)
RHS = np.linalg.norm(a) + np.linalg.norm(b)
print('LHS:', LHS)
print('RHS:', RHS)

In [48]:
# Distance (way to calculate distance between 2 points)

a = np.array([1.8, 2.0, -3.7, 4.7])
b = np.array([0.6, 2.1, 1.9, -1.4])

print(np.linalg.norm(a - b))

In [49]:
# Way to calculate Standard Deviation

a = np.random.random(100)
stdev = lambda x: np.linalg.norm(x - sum(x)/len(x))/(len(x)**0.5)
print(stdev(a))

# Other way
print(np.std(a))

In [50]:
def gram_schmidt(a):
    q = []
    for i in range(len(a)):
        
        #orthogonalization
        q_tilde = a[i]
        for j in range(len(q)):
            q_tilde = q_tilde - (q[j] @ a[i])*q[j]
        
        #Test for dependennce
        if np.sqrt(sum(q_tilde**2)) <= 1e-10:
            print('Vectors are linearly dependent.')
            print('GS algorithm terminates at iteration ', i+1)
            return q
        
        #Normalization
        else:
            q_tilde = q_tilde / np.sqrt(sum(q_tilde**2))
            q.append(q_tilde)
    print('Vectors are linearly independent.')
    return q

In [51]:
a = np.array([ [-1, 1, -1, 1], [-1, 3, -1, 3], [1, 3, 5, 7] ])
q = gram_schmidt(a)
print(q)
#Test orthonormality
print('Norm of q[0] :', (sum(q[0]**2))**0.5)
print('Inner product of q[0] and q[1] :', q[0] @ q[1])
print('Inner product of q[0] and q[2] :', q[0] @ q[2])
print('Norm of q[1] :', (sum(q[1]**2))**0.5)
print('Inner product of q[1] and q[2] :', q[1] @ q[2])
print('Norm of q[2] :', (sum(q[2]**2))**0.5)

In [52]:
b = np.array([a[0], a[1], 1.3*a[0] + 0.5*a[1]])
q = gram_schmidt(b)
print(q)

In [53]:
def QR_factorization(A):
    Q_transpose = np.array(gram_schmidt(A.T))
    R = Q_transpose @ A
    Q = Q_transpose.T
    return Q, R

Q, R = QR_factorization(np.random.normal(size = (6,4)))
print(Q, R)